//
// This file is part of prose-app-macos.
// Copyright (c) 2022 Prose Foundation
//

import Assets
import ProseUI
import SwiftUI

struct AuthenticationView: View {
  var body: some View {
    ScrollView(.vertical, showsIndicators: false) {
      VStack(spacing: 24) {
        ContentSection(
          header: "Account password",
          footer: """
          Your password is what keeps your account secure. If you forget it, you can still recover it from your recovery email. **Make sure to keep it up-to-date.**
          """
        ) {
          VStack(alignment: .leading) {
            ThreeColumns {
              Text("Password:")
            } column2: {
              Button {} label: {
                Text(verbatim: "Change password…")
                  .frame(maxWidth: .infinity)
              }
              .controlSize(.large)
            } column3: {
              EmptyView()
            }
            HStack {
              Text(verbatim: "Recovery email:")
                .bold()
              Text(verbatim: "baptiste@jamin.me")
              Button {} label: {
                Text(verbatim: "Edit")
              }
              .controlSize(.small)
            }
          }
          .padding(.horizontal)
        }
        Divider()
          .padding(.horizontal)
        ContentSection(
          header: "Multi-factor authentication",
          footer: """
          Multi-factor authentication adds an extra layer of security to your account, by asking for a temporary code generated by an app, upon login.

          In the event that you are unable to generate MFA tokens, you can still use your recovery phone number to login to your account.
          """
        ) {
          VStack(alignment: .leading) {
            ThreeColumns {
              Text("Token:")
            } column2: {
              Button {} label: {
                Text(verbatim: "Disable MFA…")
                  .frame(maxWidth: .infinity)
              }
              .controlSize(.large)
            } column3: {
              EmptyView()
            }
            HStack {
              Text(verbatim: "Status:")
                .bold()
              HStack(spacing: 4) {
                // TODO: Change this to a more general purpose indicator
                OnlineStatusIndicator(.online)
                Text(verbatim: "Enabled")
              }
            }
            HStack {
              Text(verbatim: "Recovery phone:")
                .bold()
              Text(verbatim: "+33631893345")
              Button {} label: {
                Text(verbatim: "Edit")
              }
              .controlSize(.small)
            }
          }
          .padding(.horizontal)
        }
      }
      .padding(.vertical, 24)
    }
  }
}

struct AuthenticationView_Previews: PreviewProvider {
  static var previews: some View {
    AuthenticationView()
      .frame(width: 480, height: 512)
  }
}
